name: Artifacts
on: [workflow_dispatch]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Make Artifacts
        run: |
          echo Hello from Github Action > hello.txt
          echo Hello World > world.txt
      - name: Assemble Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "Artifacts"
          path: |
            hello.txt
            world.txt
  get:
    needs: make
    runs-on: ubuntu-latest
    steps:
      - name: Read Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Artifacts
      - name: Read folder
        run: ls
      - name: Read files
        run: |
          cat hello.txt
          cat world.txt
